### ISSUE TITLE
Completar FAQ

### ISSUE THREAD

**Issue by palomapiot** [hellosisters/hellosisters.github.io#12]
- [x] explicar que é HS
- [x] explicar os workshops
- [x] engadir SLACK como método de comunicación habitual
- [x] explicar que nos reunimos unha vez ó mes
- [x] que facemos en cada reunión
- [x] como se pode unir unha nova sister

**Comment by aidawhale** [comment]
O contido está todo ben, soamente vou pedir que cambies algunhas cousas que en galego non son correctas:

1. Subtítulo FAQ: "podas" -> "poidas".
2. Ao/ó, está ben usar tanto "ó" como "ao", soamente temos que manter o uso de "ao" durante todo o que se escriba na web.
3. FAQ 3 - "red social e te enviaremos" -> "rede social e enviarémosche".
4. FAQ 4 - "quera" -> "queira".
5. Xa que ten relación con isto, na barra de navegación, ó "máis" está sin til, poderías engadilo?.

😄
