### ISSUE TITLE
Editar README

### ISSUE THREAD

**Issue by aidawhale** [hellosisters/hellosisters.github.io#30]
- [x] Editar "Metodoloxía de traballo" para aclarar o fluxo.
- [x] Revisar que /img sexa /img/sisters.
- [x] Editar "Engadir unha nova sister no equipo": engadir neste punto que se visualizarán 3 sisters en cada fila, e que de ser preciso, crear unha nova fila e recordar poñer o col-sm-4.
- [x] Revisar ruta xa se podes "/blog-item/blog-..."

**Comment by lauramcastro** [comment]
Unha dúbida: os puntos 4 e 5 da metodoloxía de traballo non deberían estar invertidos? Fálase de ligar a rama á _issue_, pero o que se liga á _issue_ é a PR, e nese punto (4) a PR aínda non está creada.

**Comment by aidawhale** [comment]
Si, efectivamente estaban do revés e ademais confundírame ó explicar o tema rama/PR. Xa está corrixido.

Gracias!!
